INSERT INTO consultants (name, profile_image_url, change_status, probable_extension_status)
VALUES ('Adam Sambrink', 'https://app.momang.io/content/hejare-84007/adam-sambrink-1bfa2/picture-701ed.png', 'Ja', 'Nej'),
('Agnes Forsberg', 'https://app.momang.io/content/hejare-84007/agnes-forsberg-c2a07/picture-7d989.png', 'Ja', 'Nej'),
('Amanda Krohn', 'https://app.momang.io/content/hejare-84007/amanda-krohn-abd6d/picture-d205d.png', 'Ja', 'Nej'),
('Angelina Gudmundsson', 'https://app.momang.io/content/hejare-84007/angelina-5ac83/picture-cb5d8.png', 'Ja', 'Nej'),
('Anna Gustavsson', 'https://app.momang.io/content/hejare-84007/anna-428fc/picture-c6211.png', 'Ja', 'Nej'),
('Benny Tieu', 'https://app.momang.io/content/hejare-84007/benny-tieu-baf5c/picture-42457.png', 'Ja', 'Nej'),
('Carl Lidman', 'https://app.momang.io/content/hejare-84007/carl-lidman-fafe7/picture-c66c8.jpeg', 'Ja', 'Nej'),
('Carl-Oscar Erneholm', 'https://app.momang.io/content/hejare-84007/carl-oscar-erneholm-7e00e/picture-4ff2c.png', 'Ja', 'Nej'),
('Damien Jones', 'https://app.momang.io/content/hejare-84007/damien-jones-1e999/picture-f4955.png', 'Ja', 'Nej'),
('Daniel Molin', 'https://app.momang.io/content/hejare-84007/daniel-molin-602e8/picture-69cbd.png', 'Ja', 'Nej'),
('Daniel Roos', 'https://app.momang.io/content/hejare-84007/daniel-roos-85f8d/picture-9dd2b.png', 'Ja', 'Nej'),
('Emil Wihlander', 'https://app.momang.io/content/hejare-84007/emil-wihlander-9a259/picture-6defd.png', 'Ja', 'Nej'),
('Emilia Gjöthlen', 'https://app.momang.io/content/hejare-84007/emilia-gjothlen-7994b/picture-2b5c9.png', 'Ja', 'Nej'),
('Erik Allmér', 'https://app.momang.io/content/hejare-84007/erik-allmer-a8ce2/picture-a41ba.png', 'Ja', 'Nej'),
('Erik Björck', 'https://app.momang.io/content/hejare-84007/erik-bjorck-dab45/picture-29e1a.png', 'Ja', 'Nej'),
('Gustaf Liljegren', 'https://app.momang.io/content/hejare-84007/gustaf-liljegren-09488/picture-a37f8.png', 'Ja', 'Nej'),
('Jennifer Larsson', 'https://app.momang.io/content/hejare-84007/jennifer-larsson-e2813/picture-bba12.png', 'Ja', 'Nej'),
('John Turesson', 'https://app.momang.io/content/hejare-84007/john-turesson-1dbb0/picture-ffa66.png', 'Ja', 'Nej'),
('Kevin Hoogendijk', 'https://app.momang.io/content/hejare-84007/kevin-afc35/picture-45df9.png', 'Ja', 'Nej'),
('Kristoffer Gunnarsson', 'https://app.momang.io/content/hejare-84007/kristoffer-gunnarsson-f7962/picture-3d2c3.png', 'Ja', 'Nej'),
('Leif Tysell Sundkvist', 'https://app.momang.io/content/hejare-84007/leif-tysell-sundkvist-f8620/picture-96489.png', 'Ja', 'Nej'),
('Malin Jofjärd Lövgren', 'https://app.momang.io/content/hejare-84007/malin-jofjard-lovgren-555cf/picture-da23a.png', 'Ja', 'Nej'),
('Martin Smedmark', 'https://app.momang.io/content/hejare-84007/martin-smedmark-c0f11/picture-c28ba.png', 'Ja', 'Nej'),
('Oscar Björkman', 'https://app.momang.io/content/hejare-84007/oscar-bjorkman-3af51/picture-47f00.png', 'Ja', 'Nej'),
('Sebastian Gustafsson', 'https://app.momang.io/content/hejare-84007/sebastian-gustafsson-7df9d/picture-aedfb.png', 'Ja', 'Nej'),
('Stina Strandberg', 'https://app.momang.io/content/hejare-84007/stina-strandberg-b97e9/picture-632ff.png', 'Ja', 'Nej'),
('Svante Martinsson', 'https://app.momang.io/content/hejare-84007/svante-martinsson-8ae31/picture-2d8de.png', 'Ja', 'Nej');
